version: '3.5'

services:
  db:
    image: "postgres:12-alpine"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/data/postgres
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  api:
    build:
      context: ./
      args:
        NODE_ENV: development
    depends_on:
      - db
    environment:
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3001
      - DATABASE_URL=postgres://postgres:secret@db:5432/apidb_dev
      - DATABASE_DEBUG=false
    ports:
      - "3000:3000"
      - "127.0.0.1:9229:9229" # V8 inspector for tools/run.js
      - "127.0.0.1:9230:9230" # V8 inspector for src/start.js
    networks:
      - postgres
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./knexfile.js:/usr/src/app/knexfile.js
    command: yarn run dev

  # redis:
  #   image: redis:5.0-alpine
  #   command: ["redis-server", "--appendonly", "yes"]
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/data
  #   networks:
  #     - redis
  #   restart: unless-stopped

networks:
  postgres:
    driver: bridge
  # redis:
  #   driver: bridge

volumes:
  pg-data:
  yarn:
  pgadmin:
  # redis-data:
